version: "3.8"

services:
  mongodb-exporter:
    image: bitnami/mongodb-exporter:latest
    ports:
      - "9216:9216"
    env_file:
      - .env
    environment:
      - MONGODB_URI=${MONGO_URI}
      - MONGODB_ENABLE_COLLECTION_STATS=true
    command:
      - --mongodb.uri=${MONGO_URI}
      - --no-mongodb.direct-connect
    # depends_on:
    #   - mongo
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=5d'
      - '--storage.tsdb.retention.size=10GB'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

volumes:
  grafana_data:
